#!/bin/bash

function choose {

	local default="$1"
	local prompt="$2"
	local yes="$3"
	local no="$4"
	local answer
	
	read -p "$prompt" answer
	[ -z "$answer" ] && answer="$default"
	
	case "$answer" in
		[yY1] ) exec "$yes"
			;;
		[nN0] ) exec "$no"
			;;
		*     ) printf "%b" "Unexpected answer '$answer'!" >&2 ;;
	esac
}

choose
